// Copyright (c) 2026 Macskásy Attila (ATAILA)
// SPDX-License-Identifier: MPL-2.0

// Command gendesc writes the contract's property descriptions as Go, so that
// the provider's nested attributes carry the contract's own text where the
// provider has none of its own.
//
//	go run ../../scripts/gendesc -in ../../api/openapi-v1.json -out descriptions.gen.go
//
// (run by `go generate ./internal/client`). For every object schema of
// components.schemas it records, keyed "Schema.property", the property's
// description (its own, else that of the schema it refers to) and, for a
// property that refers to an object schema (directly, as a nullable or as the
// items of a list), that schema's name, so that nested properties resolve.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type schema struct {
	Ref         string            `json:"$ref"`
	Type        any               `json:"type"`
	Description string            `json:"description"`
	Properties  map[string]schema `json:"properties"`
	Items       *schema           `json:"items"`
	AnyOf       []schema          `json:"anyOf"`
	OneOf       []schema          `json:"oneOf"`
	AllOf       []schema          `json:"allOf"`
}

func main() {
	in := flag.String("in", "", "the OpenAPI contract")
	out := flag.String("out", "", "the Go file to write")
	pkg := flag.String("package", "client", "the Go package")
	flag.Parse()
	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "gendesc: -in and -out are required")
		os.Exit(2)
	}
	src, err := Generate(*in, *pkg)
	if err == nil {
		err = os.WriteFile(*out, src, 0o644)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendesc:", err)
		os.Exit(1)
	}
}

// Generate returns the Go source for the contract at path.
func Generate(path, pkg string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var spec struct {
		Components struct {
			Schemas map[string]schema `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(raw, &spec); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	schemas := spec.Components.Schemas
	descs := map[string]string{}
	refs := map[string]string{}
	for name, s := range schemas {
		for prop, p := range s.Properties {
			key := name + "." + prop
			target := refOf(p)
			d := strings.TrimSpace(p.Description)
			if d == "" && target != "" {
				d = strings.TrimSpace(schemas[target].Description)
			}
			if d != "" {
				descs[key] = d
			}
			if target != "" && len(schemas[target].Properties) > 0 {
				refs[key] = target
			}
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by scripts/gendesc from the API contract; DO NOT EDIT.\n\npackage %s\n\n", pkg)
	b.WriteString("// contractDescriptions is the description of each property of each object\n")
	b.WriteString("// schema of the contract, keyed \"Schema.property\".\n")
	b.WriteString("var contractDescriptions = map[string]string{\n")
	for _, k := range sortedKeys(descs) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, descs[k])
	}
	b.WriteString("}\n\n")
	b.WriteString("// contractRefs names the object schema a property refers to (directly, as a\n")
	b.WriteString("// nullable or as the items of a list), keyed \"Schema.property\".\n")
	b.WriteString("var contractRefs = map[string]string{\n")
	for _, k := range sortedKeys(refs) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, refs[k])
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// refOf is the schema a property refers to, through nullables and lists.
func refOf(s schema) string {
	if s.Ref != "" {
		return s.Ref[strings.LastIndex(s.Ref, "/")+1:]
	}
	for _, group := range [][]schema{s.AllOf, s.AnyOf, s.OneOf} {
		for _, x := range group {
			if r := refOf(x); r != "" {
				return r
			}
		}
	}
	if s.Items != nil {
		return refOf(*s.Items)
	}
	return ""
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
