// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OperationStatus.
const (
	AwaitingApproval OperationStatus = "awaiting_approval"
	AwaitingOperator OperationStatus = "awaiting_operator"
	Failed           OperationStatus = "failed"
	Pending          OperationStatus = "pending"
	Running          OperationStatus = "running"
	Succeeded        OperationStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case AwaitingApproval:
		return true
	case AwaitingOperator:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// LicenceSummary defines model for LicenceSummary.
type LicenceSummary struct {
	DaysRemaining *int    `json:"days_remaining,omitempty"`
	State         string  `json:"state"`
	StateReason   *string `json:"state_reason,omitempty"`
}

// Meta defines model for Meta.
type Meta struct {
	ApiVersion      string         `json:"api_version"`
	Licence         LicenceSummary `json:"licence"`
	Modules         *[]string      `json:"modules,omitempty"`
	PlatformVersion string         `json:"platform_version"`
	TenancyMode     *string        `json:"tenancy_mode,omitempty"`
	Tier            *string        `json:"tier,omitempty"`
}

// Operation defines model for Operation.
type Operation struct {
	CreatedAt    *string                 `json:"created_at,omitempty"`
	Error        *map[string]interface{} `json:"error,omitempty"`
	Id           string                  `json:"id"`
	Kind         string                  `json:"kind"`
	Message      *string                 `json:"message,omitempty"`
	ResourceId   *string                 `json:"resource_id,omitempty"`
	ResourceType *string                 `json:"resource_type,omitempty"`
	Status       OperationStatus         `json:"status"`
	UpdatedAt    *string                 `json:"updated_at,omitempty"`
}

// OperationStatus defines model for Operation.Status.
type OperationStatus string

// Problem The OpenAPI shape of an error. Extra members may appear (for example the
// licence refusal's “state“/“remedy“ or a validation “errors“ list).
type Problem struct {
	Code                 string                 `json:"code"`
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	RequestId            *string                `json:"request_id,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Whoami defines model for Whoami.
type Whoami struct {
	AuthKind  string          `json:"auth_kind"`
	ExpiresAt *string         `json:"expires_at,omitempty"`
	Principal WhoamiPrincipal `json:"principal"`
	Scopes    []string        `json:"scopes"`
	Token     *WhoamiToken    `json:"token,omitempty"`
}

// WhoamiPrincipal defines model for WhoamiPrincipal.
type WhoamiPrincipal struct {
	Email string `json:"email"`
	Id    string `json:"id"`
	Kind  string `json:"kind"`
	Name  string `json:"name"`
}

// WhoamiToken defines model for WhoamiToken.
type WhoamiToken struct {
	AllowDestroy  bool     `json:"allow_destroy"`
	GrantedScopes []string `json:"granted_scopes"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Prefix        string   `json:"prefix"`
}

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.RequestId != nil {
		object["request_id"], err = json.Marshal(a.RequestId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// MetaGet API and platform facts
	//
	// Corresponds with GET /meta (the `MetaGet` operationId).
	MetaGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OperationsGet One operation
	//
	// Corresponds with GET /operations/{operation_id} (the `OperationsGet` operationId).
	OperationsGet(ctx context.Context, operationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WhoamiGet The calling principal
	//
	// Corresponds with GET /whoami (the `WhoamiGet` operationId).
	WhoamiGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// MetaGet API and platform facts
//
// Corresponds with GET /meta (the `MetaGet` operationId).
func (c *Client) MetaGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetaGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OperationsGet One operation
//
// Corresponds with GET /operations/{operation_id} (the `OperationsGet` operationId).
func (c *Client) OperationsGet(ctx context.Context, operationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOperationsGetRequest(c.Server, operationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// WhoamiGet The calling principal
//
// Corresponds with GET /whoami (the `WhoamiGet` operationId).
func (c *Client) WhoamiGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWhoamiGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewMetaGetRequest constructs an http.Request for the MetaGet method
func NewMetaGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meta")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOperationsGetRequest constructs an http.Request for the OperationsGet method
func NewOperationsGetRequest(server string, operationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "operation_id", operationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWhoamiGetRequest constructs an http.Request for the WhoamiGet method
func NewWhoamiGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/whoami")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// MetaGetWithResponse API and platform facts
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /meta (the `MetaGet` operationId).
	MetaGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetaGetResponse, error)

	// OperationsGetWithResponse One operation
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /operations/{operation_id} (the `OperationsGet` operationId).
	OperationsGetWithResponse(ctx context.Context, operationId string, reqEditors ...RequestEditorFn) (*OperationsGetResponse, error)

	// WhoamiGetWithResponse The calling principal
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /whoami (the `WhoamiGet` operationId).
	WhoamiGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WhoamiGetResponse, error)
}

type MetaGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Meta
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r MetaGetResponse) GetJSON200() *Meta {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r MetaGetResponse) GetJSONDefault() *Problem {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r MetaGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MetaGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetaGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MetaGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type OperationsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Operation
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r OperationsGetResponse) GetJSON200() *Operation {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r OperationsGetResponse) GetJSONDefault() *Problem {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r OperationsGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OperationsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OperationsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OperationsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type WhoamiGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Whoami
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r WhoamiGetResponse) GetJSON200() *Whoami {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r WhoamiGetResponse) GetJSONDefault() *Problem {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r WhoamiGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r WhoamiGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WhoamiGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r WhoamiGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// MetaGetWithResponse API and platform facts
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /meta (the `MetaGet` operationId).
func (c *ClientWithResponses) MetaGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetaGetResponse, error) {
	rsp, err := c.MetaGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetaGetResponse(rsp)
}

// OperationsGetWithResponse One operation
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /operations/{operation_id} (the `OperationsGet` operationId).
func (c *ClientWithResponses) OperationsGetWithResponse(ctx context.Context, operationId string, reqEditors ...RequestEditorFn) (*OperationsGetResponse, error) {
	rsp, err := c.OperationsGet(ctx, operationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOperationsGetResponse(rsp)
}

// WhoamiGetWithResponse The calling principal
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /whoami (the `WhoamiGet` operationId).
func (c *ClientWithResponses) WhoamiGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WhoamiGetResponse, error) {
	rsp, err := c.WhoamiGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWhoamiGetResponse(rsp)
}

// ParseMetaGetResponse parses an HTTP response from a MetaGetWithResponse call
func ParseMetaGetResponse(rsp *http.Response) (*MetaGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetaGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Meta
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseOperationsGetResponse parses an HTTP response from a OperationsGetWithResponse call
func ParseOperationsGetResponse(rsp *http.Response) (*OperationsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OperationsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseWhoamiGetResponse parses an HTTP response from a WhoamiGetWithResponse call
func ParseWhoamiGetResponse(rsp *http.Response) (*WhoamiGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WhoamiGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Whoami
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
